[books.a-drop-of-corruption]
title = "A Drop of Corruption"
author = "Robert Jackson Bennett"
format = "text"
genres = ["fantasy", "mystery"]
finished = 2026-01-01
media = "ebook"
via = "Libby"
grade = "A-"
pages = 458

[books.life-after-cars]
title = "Life After Cars"
author = ["Sarah Goodyear", "Doug Gordon", "Aaron Naparstek"]
format = "text"
genres = ["non-fiction"]
finished = 2026-01-01
media = "paper"
via = "own"
grade = "A-"
pages = 233

[books.the-journalist-and-the-murderer]
title = "The Journalist and the Murderer"
author = "Janet Malcolm"
format = "text"
genres = ["non-fiction"]
finished = 2026-01-07
media = "ebook"
via = "own"
grade = "B+"
pages = 178

[books.built-from-broken]
title = "Built from Broken"
author = "Scott Hogan"
format = "text"
genres = ["non-fiction"]
finished = 2026-01-08
media = "paper"
via = "own"
grade = "A"
pages = 319

[books.i-robot]
title = "I, Robot"
author = "Isaac Asimov"
format = "text"
genres = ["science fiction"]
finished = 2026-01-20
media = "ebook"
via = "Libby"
grade = "B+"
pages = 256

[books.on-the-shortness-of-life]
title = "On the Shortness of Life"
author = "Seneca"
format = "text"
genres = ["non-fiction"]
finished = 2026-01-22
media = "paper"
via = "own"
grade = "B"
pages = 147
