[books.a-drop-of-corruption]
title = "A Drop of Corruption"
author = "Robert Jackson Bennett"
format = "text"
genres = ["fantasy", "mystery"]
finished = 2026-01-01
media = "ebook"
via = "Libby"
grade = "A-"
pages = 458

[books.life-after-cars]
title = "Life After Cars"
author = ["Sarah Goodyear", "Doug Gordon", "Aaron Naparstek"]
format = "text"
genres = ["non-fiction"]
finished = 2026-01-01
media = "paper"
via = "own"
grade = "A-"
pages = 233

[books.built-from-broken]
title = "Built from Broken"
author = "Scott Hogan"
format = "text"
genres = ["non-fiction"]
finished = 2026-01-07
media = "paper"
via = "own"
grade = "A"
pages = 319
